### ISSUE TITLE
Help Compiling

### ISSUE THREAD

**Issue by cASUAL12345** [ugackMiner53/Mitch-Client#11]
sorry, first time doing it. I downloaded the project source code, opened it with visual studio, made some changes, and i cant understand how to compile it
its missing things like UnityEngine, BepInEx, HarmonyLib, etc.

I have Unity installed, i just never used it.

**Comment by ugackMiner53** [comment]
This is because it uses BepInEx, and you need to import the following .dlls:

## From BepInEx\core
0Harmony.dll
BepInEx.dll
BepInEx.Harmony.dll


You should also try to import everything from Muck\Muck_Data\Managed for Muck specifically. (Some things will fail to import, but that should be fine)

I cannot provide these files due to copyright, but [here](https://github.com/BepInEx/BepInEx/releases/download/v5.4.11/BepInEx_x64_5.4.11.0.zip) is a link to BepInEx.


I'll try to provide better build instructions in the future
