### ISSUE TITLE
Cant remove mitch client or run it (exe)

### ISSUE THREAD

**Issue by Thebostongamer** [ugackMiner53/Mitch-Client#18]
I need permission to run and uninstall even after giving admin.

**Comment by ugackMiner53** [comment]
This is not part of Mitch Client, the installer was created with [Inno](https://jrsoftware.org/isinfo.php), and is most likely a problem with your system.

The installer requires permission to install because most people have Muck installed in their "Program Files" directory, which you need admin permission to access, so the installer has to ask for admin.

If you don't have administrator permission on your computer, that is your fault, and not part of Mitch.
